config/routes.rb
Shoes1::Application.routes.draw do
  root to: 'shoes#index'
  resources :shoes do
    resources :parts
  end
  resources :matters
  resources :partypes do
    resources :matters, controller: :partype_matters,
                        only: [:index, :new]
  end

  get '/partypes/:partype_id/matters/:id/add', to: 'partype_matters#add', as: 'add_partype_matter'
  get '/partypes/:partype_id/matters/:id/remove', to: 'partype_matters#destroy', as: 'remove_partype_matter'

  resources :colors

  get '/shoes/:shoe_id/select_color',                 to: 'colors#select',  as: 'shoe_color'
  get '/shoes/:shoe_id/parts/:part_id/select_partype',to: 'partypes#select',as: 'part_partype'
  get '/shoes/:shoe_id/parts/:part_id/select_matter/:partype_id',
                                                      to: 'matters#select', as: 'part_matter'

  get '/partypes/:partype_id/matters/:matter_id/select_matter/',to: 'matters#select', as: 'part_matter_no_partype'
end

app/views/crudable/_form.html.haml
= form_for @record, form_params(@record, action_name) do |f|
  - if @record.errors.any?
    #error_explanation
      %h2= "#{pluralize(@record.errors.count, "error")} prohibited this #{@model.name} from being saved:"
      %ul
        - @record.errors.full_messages.each do |msg|
          %li= msg

  - @record.fields.each do |field|
    .field
      - if field.selectable
        = render 'crudable/selectable_field', f: f, field: field
      - elsif field.invisible
        = f.hidden_field "#{field.name}_id"
      - else
        = f.label field.label
        = f.text_field field.name
  - unless @record.new_record?
    - @record.collections.each_with_index do |c, index|
      .field
        - name = @model.collections_names[index].to_s
        = "#{name.classify.pluralize}:"
        = c.map(&:to_s).join(', ')
        - if @model.collections_editable[index]
          = link_to "Edit #{name} collection", edit_collection_path(@record, name)

  .actions
    = f.submit 'Save'

app/views/crudable/_selectable_field.html.haml
%b= "#{field.name.to_s.classify}:"
= selectable_field_input_tag(@record, field, @selected)
= selectable_field_value(@record, field, @selected)
= link_to "Select #{field.name}", select_path(@record, field.name, @selected)

app/views/crudable/edit.html.haml
%h1
  = "Editing #{@record.name}"

= render 'crudable/form'

= link_to 'Show', path_for(@record, :show)
\|
= link_to 'Back', model_path(@model)

app/views/crudable/index.html.haml
%h1
  - if @select
    = "Select #{@model.name}"
  - else
    = @model.name.pluralize

%table
  %tr
    - @model.fields_names.each do |f_name|
      %th= f_name
    - @model.collections_names.each do |c_name|
      %th= c_name
    %th
    - unless @select
      %th
      %th

  - @records.each do |record|
    %tr{ id: "#{@model.name.downcase}_record_#{record.id}" }
      - record.fields.each do |f|
        %td= record.send(f.name)
      - record.collections.each do |c|
        %td= c.to_a.map{ |e| e.to_s }.to_s
      - if @select
        %td= link_to select_link_name(@model, @select), path_for_selected(record, @select)
      - else
        %td= link_to "Show #{@model.name.downcase}", path_for(record, :show)
        %td= link_to "Edit #{@model.name.downcase}", path_for(record, :edit)
        %td= link_to "Destroy #{@model.name.downcase}", path_for(record, :destroy), method: :delete, data: { :confirm => 'Are you sure?' }
%br

- unless @do_not_show_add_link
  = link_to add_link_name(@model, controller_name), add_link_path(@model, controller_name, @partype_id)

app/views/crudable/new.html.haml
%h1= "New #{@model.name}"

= render 'crudable/form'

= link_to 'Back', model_path(@model)

app/views/crudable/show.html.haml
%p#notice= notice
%h1= @model.name
- @model.fields_names.each do |f|
  %p
    %b= "#{f}:"
    = @record.send(f)
- @model.collections_names.each_with_index do |c, index|
  %p
    %b= "#{c}:"
    = @record.collections[index].map(&:name)

= link_to 'Edit', path_for(@record, :edit)
\|
= link_to 'Back', model_path(@model)